"""
CISD velocity-gauge atomic polar tensors - CIwfn.velocity_dipole_derivatives()\n(the correlation block) through the pycc.apt(gauge='velocity') facade: the\nwave-function-overlap formulation, -2 (Icc + Icphi + Iphic + Iphiphi) with the\nvector-potential (linear momentum) CPCI response.

Reference generated by the standalone validated CISD-VCD
implementation (cisd_vcd.py / cisd_apt_lg.py / cisd_analytic_hessian.py;
A. Krishnan, June 2026), at the geometry below.  That implementation was
itself validated independently: the analytic Hessian against Psi4/Gaussian
finite differences (~1e-6), the AATs against the determinant-based apyib
reference (B. Shumberger; ~1e-11 a.u.), and the LG-APT (Z-vector route)
against finite differences of the analytic dipole.  The CIwfn port
reproduces these values to ~1e-10.  The references are TOTAL tensors, so
the tests exercise the full facade decomposition (nuclear + HF reference +
CISD correlation).  Spatial orbitals, all-electron only.
"""

import numpy as np
import pycc


# Reference TOTAL VG APT [3*atom + beta, alpha], (P)-H2O2/STO-3G.
VG_APT_REF = np.array([
 [ 0.9565985610, 0.2404439930,-0.0000006788],
 [ 0.1774893329, 0.1555861277, 0.0000019628],
 [-0.0000004434, 0.0000018991, 0.8551121460],
 [ 0.9565985610, 0.2404439930, 0.0000006761],
 [ 0.1774893329, 0.1555861277,-0.0000019592],
 [ 0.0000004413,-0.0000018960, 0.8551121460],
 [ 6.8024442952, 0.0624854667,-0.0000009738],
 [ 0.1250980895, 7.0795865038, 0.0000030620],
 [-0.0000011688, 0.0000029529, 8.0926181418],
 [ 6.8024442952, 0.0624854667, 0.0000009844],
 [ 0.1250980895, 7.0795865038,-0.0000030555],
 [ 0.0000011790,-0.0000029459, 8.0926181418],
])


def test_cisd_vg_apt_vs_reference(cisd_h2o2):
    """The facade total (via CIderiv.velocity_dipole_derivatives(), migrated
    verbatim from the retired on-CIwfn overlap code) reproduces the
    standalone validated reference, every element."""
    P = np.asarray(pycc.apt(cisd_h2o2(), gauge='velocity').total).reshape(-1, 3)
    assert np.max(np.abs(P - VG_APT_REF)) < 1e-9, np.max(np.abs(P - VG_APT_REF))
