"""
CISD atomic axial tensors - CIwfn.atomic_axial_tensors() (the correlation\nblock) through the pycc.aat facade: the wave-function-overlap formulation\n(Krishnan, Shumberger & Crawford), Icc + Icphi + Iphic + Iphiphi with the\nmagnetic-field CPCI response of the true-normalized CI amplitudes.

Reference provenance: generated by the standalone validated CISD-VCD
implementation (cisd_vcd.py / cisd_apt_lg.py / cisd_analytic_hessian.py;
A. Krishnan, June 2026), at the geometry below.  That implementation was
itself validated independently: the analytic Hessian against Psi4/Gaussian
finite differences (~1e-6), the AATs against the determinant-based apyib
reference (B. Shumberger; ~1e-11 a.u.), and the LG-APT (Z-vector route)
against finite differences of the analytic dipole.  The CIwfn port
reproduces these values to ~1e-10; the test tolerance (1e-6) absorbs the
printed precision of the reference.  The references are TOTAL tensors, so
the tests exercise the full facade decomposition (nuclear + HF reference +
CISD correlation).  Spatial orbitals, all-electron only.
"""

import numpy as np
import pycc


# Reference TOTAL AAT [3*atom + beta, alpha], (P)-H2O2/STO-3G.
AAT_REF = np.array([
 [-0.0245586668, 0.0977047211,-0.3532345859],
 [-0.0158908913, 0.0181292780,-0.0917113603],
 [ 0.1522781165, 0.3409913695,-0.0000007363],
 [-0.0245586651, 0.0977047208, 0.3532345859],
 [-0.0158908916, 0.0181292762, 0.0917113604],
 [-0.1522781168,-0.3409913697,-0.0000007362],
 [-0.0063821715, 0.6947952006, 0.2131056766],
 [-0.7231023900, 0.0127783589,-2.1375592252],
 [-0.2035256543, 2.2788946007,-0.0000010351],
 [-0.0063821716, 0.6947951795,-0.2131056766],
 [-0.7231023702, 0.0127783579, 2.1375592251],
 [ 0.2035256536,-2.2788945997,-0.0000010340],
])

# Same, (P)-H2O2/cc-pVDZ - a real virtual space (virtuals in every irrep,
# polarization functions) that STO-3G's two virtuals cannot provide.
AAT_REF_CCPVDZ = np.array([
 [-0.0086864882,  0.0460210947, -0.2786642140],
 [-0.0144315579,  0.0047404923, -0.0413297936],
 [ 0.2754861449,  0.2323528949, -0.0000004948],
 [-0.0086864882,  0.0460210948,  0.2786642140],
 [-0.0144315596,  0.0047404909,  0.0413297941],
 [-0.2754861451, -0.2323528949, -0.0000004934],
 [-0.0086586168,  0.2907045614,  0.1612513739],
 [-0.3149341376,  0.0125920517, -0.6588530005],
 [-0.2451662663,  0.7559376141, -0.0000003548],
 [-0.0086586161,  0.2907045538, -0.1612513739],
 [-0.3149341301,  0.0125920510,  0.6588530000],
 [ 0.2451662660, -0.7559376135, -0.0000003548],
])


def test_cisd_aat_vs_reference(cisd_h2o2):
    """The facade total reproduces the standalone validated reference, every
    element (STO-3G)."""
    P = np.asarray(pycc.aat(cisd_h2o2()).total).reshape(-1, 3)
    assert np.max(np.abs(P - AAT_REF)) < 1e-6, np.max(np.abs(P - AAT_REF))


def test_cisd_aat_ccpvdz_vs_reference(cisd_h2o2):
    """Larger basis (cc-pVDZ): the facade total reproduces the standalone
    validated reference, every element."""
    P = np.asarray(pycc.aat(cisd_h2o2(basis='cc-pVDZ')).total).reshape(-1, 3)
    assert np.max(np.abs(P - AAT_REF_CCPVDZ)) < 1e-6, np.max(np.abs(P - AAT_REF_CCPVDZ))
