"""
CISD molecular (nuclear) Hessian - pycc.hessian(pycc.CIderiv(ci)) facade. 
hessian() is inherited from CorrelatedDerivs (the 2n+1 route, no second-order CPHF), 
driven by CIderiv's density hooks - no CISD-specific Hessian code.

Reference provenance: generated by the standalone validated CISD-VCD
implementation (cisd_vcd.py / cisd_apt_lg.py / cisd_analytic_hessian.py;
A. Krishnan, June 2026), at the geometry below.  That implementation was
itself validated independently: the analytic Hessian against Psi4/Gaussian
finite differences, the AATs against the determinant-based apyib
reference (B. Shumberger; ~1e-11 a.u.), and the LG-APT (Z-vector route)
against finite differences of the analytic dipole.  The CIwfn port
reproduces these values to ~1e-10; the test tolerance absorbs the
printed precision of the reference.  The references are TOTAL tensors, so
the tests exercise the full facade decomposition (nuclear + HF reference +
CISD correlation). 
"""

import numpy as np
import psi4
import pycc


# Reference TOTAL Hessian (3*natom x 3*natom), (P)-H2O2/STO-3G.
HESS_REF = np.array([
 [ 1.17440123e-01,-1.17600481e-01, 3.11374866e-07,-1.48695362e-02,-2.50929462e-03,-3.08954088e-08,-8.22972776e-02, 5.74035675e-02,-2.00683390e-07,-2.02733091e-02, 6.27062078e-02,-7.97960671e-08],
 [-1.17600481e-01, 4.50462612e-01,-1.16352630e-06,-2.50929462e-03, 1.46156262e-03, 1.09056100e-08, 1.35095225e-01,-4.63127973e-01, 1.19522046e-06,-1.49854499e-02, 1.12037981e-02,-4.25997658e-08],
 [ 3.11374866e-07,-1.16352630e-06, 2.75322865e-04, 3.10434256e-08,-1.08929178e-08, 2.75320484e-04,-3.32210280e-07, 1.21055938e-06,-2.75318530e-04,-1.02080115e-08,-3.61401606e-08,-2.75324818e-04],
 [-1.48695362e-02,-2.50929462e-03, 3.10434256e-08, 1.17440123e-01,-1.17600481e-01,-3.11507979e-07,-2.02733091e-02, 6.27062078e-02, 7.95038908e-08,-8.22972776e-02, 5.74035675e-02, 2.00960663e-07],
 [-2.50929462e-03, 1.46156262e-03,-1.08929178e-08,-1.17600481e-01, 4.50462612e-01, 1.16120663e-06,-1.49854499e-02, 1.12037981e-02, 4.26431001e-08, 1.35095225e-01,-4.63127973e-01,-1.19295682e-06],
 [-3.08954088e-08, 1.09056100e-08, 2.75320484e-04,-3.11507979e-07, 1.16120663e-06, 2.75322865e-04, 1.04896705e-08, 3.55192597e-08,-2.75324818e-04, 3.31913717e-07,-1.20763150e-06,-2.75318530e-04],
 [-8.22972776e-02, 1.35095225e-01,-3.32210280e-07,-2.02733091e-02,-1.49854499e-02, 1.04896705e-08, 5.10634230e-01,-4.99015461e-02, 2.19445198e-07,-4.08063643e-01,-7.02082292e-02, 1.02275412e-07],
 [ 5.74035675e-02,-4.63127973e-01, 1.21055938e-06, 6.27062078e-02, 1.12037981e-02, 3.55192597e-08,-4.99015461e-02, 5.67806150e-01,-1.24270020e-06,-7.02082292e-02,-1.15881975e-01,-3.37844056e-09],
 [-2.00683390e-07, 1.19522046e-06,-2.75318530e-04, 7.95038908e-08, 4.26431001e-08,-2.75324818e-04, 2.19445198e-07,-1.24270020e-06, 2.75281709e-04,-9.82656981e-08, 4.83664127e-09, 2.75361639e-04],
 [-2.02733091e-02,-1.49854499e-02,-1.02080115e-08,-8.22972776e-02, 1.35095225e-01, 3.31913717e-07,-4.08063643e-01,-7.02082292e-02,-9.82656981e-08, 5.10634230e-01,-4.99015461e-02,-2.23440008e-07],
 [ 6.27062078e-02, 1.12037981e-02,-3.61401606e-08, 5.74035675e-02,-4.63127973e-01,-1.20763150e-06,-7.02082292e-02,-1.15881975e-01, 4.83664127e-09,-4.99015461e-02, 5.67806150e-01, 1.23893502e-06],
 [-7.97960671e-08,-4.25997658e-08,-2.75324818e-04, 2.00960663e-07,-1.19295682e-06,-2.75318530e-04, 1.02275412e-07,-3.37844056e-09, 2.75361639e-04,-2.23440008e-07, 1.23893502e-06, 2.75281709e-04],
])


# (P)-H2O2 at the CISD-VCD validation geometry (bohr) - the same geometry the cisd_h2o2 fixture
# builds, in explicit array form so the FD recipe below can displace a single coordinate.
SYM = ['H', 'H', 'O', 'O']
BASE = np.array([[-1.938703940499,  1.630081390557, 0.408551539155],
                 [ 1.938703940499, -1.630081390557, 0.408551534619],
                 [-1.364718227128, -0.236825138192, 0.408556429577],
                 [ 1.364718227128,  0.236825138192, 0.408556416160]])


def _geom(coords):
    s = "units bohr\nsymmetry c1\nno_com\nno_reorient\n"
    for sym, xyz in zip(SYM, coords):
        s += f"{sym} {xyz[0]:.10f} {xyz[1]:.10f} {xyz[2]:.10f}\n"
    return s


def _cideriv(coords=BASE, freeze_core='false', basis='sto-3g'):
    """Converged spatial CISD derivative driver.  Mirrors test_069's ``_mpwfn``; no
    ``orbital_basis`` knob because the CIderiv path is spatial-only."""
    psi4.core.clean()
    psi4.core.clean_options()
    psi4.geometry(_geom(coords))
    psi4.set_options({'basis': basis, 'scf_type': 'pk', 'freeze_core': freeze_core,
                      'e_convergence': 1e-13, 'd_convergence': 1e-13})
    _, wfn = psi4.energy('scf', return_wfn=True)
    ci = pycc.CIwfn(wfn, model='CISD', orbital_basis='spatial')
    ci.solve_ci(e_conv=1e-13, r_conv=1e-13, maxiter=250)
    return pycc.CIderiv(ci)


def _gradfd_col(atom, cart, freeze_core='false', h=0.002):
    """Regeneration recipe for HESS_COL (not run in the tests): one correlation-Hessian column
    (3*natom,) via a 7-point O(h^6) FD of the analytic correlation GRADIENT - the first-order
    Z-vector gradient, independent of the 2n+1 Hessian code the frozen columns validate."""
    def g(delta):
        c = BASE.copy()
        c[atom, cart] += delta
        return np.asarray(_cideriv(c, freeze_core).gradient().correlation)
    return ((-g(-3 * h) + 9 * g(-2 * h) - 45 * g(-h)
             + 45 * g(h) - 9 * g(2 * h) + g(3 * h)) / (60 * h)).reshape(-1)


# Frozen analytic correlation-Hessian columns H[:, atom*3 + cart], keyed by the psi4 freeze_core
# string.  Each validated once against _gradfd_col above (5.3e-13 to 2.0e-12); analytic values,
# frozen rather than re-run.
HESS_COL = {
    'false': {
        (0, 2): np.array([-2.3086657845261643e-08, 3.4611337647058616e-08, -0.018429386406812822,
                          4.4307371275323045e-09, 7.933412195797221e-10, -0.00019996652915440336,
                          3.685490405409978e-08, -2.051220656278572e-08, 0.020235019476489438,
                          -1.8198983334613094e-08, -1.4892472308722006e-08, -0.0016056665405224436]),
        (2, 1): np.array([0.0005140849487352585, 0.03181461818370628, -2.051220627867888e-08,
                          -0.006689474623936415, -1.6127583516218312e-05, 1.4937889733557957e-08,
                          0.004383734792380734, -0.06447200830905342, 1.6900111814088386e-08,
                          0.0017916548828209719, 0.03267351770886408, -1.1325795299277075e-08]),
    },
    'true': {
        (0, 2): np.array([-2.307082688238396e-08, 3.455357577258383e-08, -0.01844074153635688,
                          4.426928346099579e-09, 7.987660394229161e-10, -0.00019987581612035036,
                          3.68753867359788e-08, -2.0448288600284902e-08, 0.02024696699632856,
                          -1.8231488197929434e-08, -1.4904053216617327e-08, -0.0016063496438515812]),
        (2, 1): np.array([0.0005213617194561385, 0.031799174763550056, -2.0448288323584213e-08,
                          -0.006692043683536468, -9.645571422776684e-06, 1.494943998440149e-08,
                          0.0044050348745609605, -0.0644758118002325, 1.683348413804105e-08,
                          0.0017656470895199162, 0.032686282608105924, -1.1334635829104613e-08]),
    },
}



# Water / 6-31G for the perturbed-MO gauge-invariance check below. 
GAUGE_WATER = """
O -0.000000000000000   0.000000000000000   0.128444410656440
H  0.000000000000000  -1.415531238764228  -1.019253001167221
H  0.000000000000000   1.415531238764228  -1.019253001167221
units bohr
symmetry c1
no_com
no_reorient
"""


def _cideriv_water(freeze_core='false', basis='6-31G'):
    """CISD derivative driver on water (no near-degenerate occupied orbitals)."""
    psi4.core.clean()
    psi4.core.clean_options()
    psi4.geometry(GAUGE_WATER)
    psi4.set_options({'basis': basis, 'scf_type': 'pk', 'freeze_core': freeze_core,
                      'e_convergence': 1e-13, 'd_convergence': 1e-13})
    _, wfn = psi4.energy('scf', return_wfn=True)
    ci = pycc.CIwfn(wfn, model='CISD', orbital_basis='spatial')
    ci.solve_ci(e_conv=1e-13, r_conv=1e-13, maxiter=250)
    return pycc.CIderiv(ci)

def test_cisd_hessian_vs_reference(cisd_h2o2):
    """The facade total (nuclear repulsion + HF reference + CISD correlation)
    reproduces the standalone validated reference, every element."""
    H = np.asarray(pycc.hessian(pycc.CIderiv(cisd_h2o2())).total)
    assert np.max(np.abs(H - HESS_REF)) < 1e-8, np.max(np.abs(H - HESS_REF))


def test_cisd_hessian_gradfd():
    """All-electron correlation-Hessian columns vs their frozen references (validated once
    against a 7-point FD of the analytic gradient to ~2e-12)."""
    H = np.asarray(_cideriv().hessian().correlation)
    for (atom, cart), ref in HESS_COL['false'].items():
        j = atom * 3 + cart
        assert np.max(np.abs(H[:, j] - ref)) < 1e-9, (atom, cart, np.max(np.abs(H[:, j] - ref)))


def test_cisd_hessian_gradfd_frozen_core():
    """Frozen-core correlation-Hessian columns vs their frozen references (validated once against
    the same 7-point gradient FD).  This is the nuclear-nuclear core<->active response: the
    frozen-core perturbed Z-vector for a nuclear perturbation, twice over."""
    cd = _cideriv(freeze_core='true')
    assert cd.ci.nfzc == 2, cd.ci.nfzc
    H = np.asarray(cd.hessian().correlation)
    for (atom, cart), ref in HESS_COL['true'].items():
        j = atom * 3 + cart
        assert np.max(np.abs(H[:, j] - ref)) < 1e-9, (atom, cart, np.max(np.abs(H[:, j] - ref)))


def test_cisd_hessian_symmetry_sum_rule(cisd_h2o2):
    """The total Hessian is symmetric and
    translationally invariant (sum over the second atom vanishes); the
    correlation block obeys both on its own."""
    comp = pycc.hessian(pycc.CIderiv(cisd_h2o2()))
    for H in (np.asarray(comp.total), np.asarray(comp.correlation)):
        assert np.max(np.abs(H - H.T)) < 1e-9
        assert np.max(np.abs(H.reshape(4, 3, 4, 3).sum(axis=2))) < 1e-9


def test_cisd_hessian_symmetry_sum_rule_frozen_core(cisd_h2o2):
    """Frozen-core counterpart of the symmetry / translational sum rule above. Reference-free: the
    correlation Hessian must stay symmetric and translationally invariant with a frozen core."""
    comp = pycc.hessian(pycc.CIderiv(cisd_h2o2(freeze_core=True)))
    H = np.asarray(comp.correlation)
    assert np.max(np.abs(H - H.T)) < 1e-9, np.max(np.abs(H - H.T))
    natom = H.shape[0] // 3
    blocks = H.reshape(natom, 3, natom, 3).sum(axis=2)
    assert np.max(np.abs(blocks)) < 1e-8, np.max(np.abs(blocks))


def test_cisd_hessian_perturbed_mo_gauge_invariance():
    """The correlation Hessian is invariant to the perturbed-MO gauge (non-canonical default vs the
    canonical dependent-pair route), all-electron and frozen-core."""
    for fc in ('false', 'true'):
        nc = np.asarray(_cideriv_water(fc).hessian().correlation)
        cd = _cideriv_water(fc)
        cd._gauge_override = 'canonical'
        ca = np.asarray(cd.hessian().correlation)
        assert np.max(np.abs(nc - ca)) < 1e-9, (fc, np.max(np.abs(nc - ca)))
