"""
CISD atomic axial tensors - CIwfn.atomic_axial_tensors() (the correlation block) through the pycc.aat facade: 
the wave-function-overlap formulation (Krishnan, Shumberger & Crawford), Icc + Icphi + Iphic + Iphiphi with the magnetic-field CPCI response of the true-normalized CI amplitudes.

Reference provenance: generated by the standalone validated CISD-VCD
implementation (cisd_vcd.py / cisd_apt_lg.py / cisd_analytic_hessian.py;
A. Krishnan, June 2026), at the geometry below.  That implementation was
itself validated independently: the analytic Hessian against Psi4/Gaussian
finite differences, the AATs against the determinant-based apyib
reference (B. Shumberger; ~1e-11 a.u.), and the LG-APT (Z-vector route)
against finite differences of the analytic dipole.  The CIwfn port
reproduces these values to ~1e-10; the test tolerance absorbs the
printed precision of the reference.  The references are TOTAL tensors, so
the tests exercise the full facade decomposition (nuclear + HF reference +
CISD correlation).  Spatial orbitals.  The hardcoded TOTAL references below are
all-electron; the apyib cross-validation at the end of this module covers both
all-electron and frozen-core, in both orbital gauges, against an outside code.
"""

import numpy as np
import psi4

import pycc
from pycc.cphf import Perturbation


# Reference TOTAL AAT [3*atom + beta, alpha], (P)-H2O2/STO-3G.
AAT_REF = np.array([
 [-0.0245586668, 0.0977047211,-0.3532345859],
 [-0.0158908913, 0.0181292780,-0.0917113603],
 [ 0.1522781165, 0.3409913695,-0.0000007363],
 [-0.0245586651, 0.0977047208, 0.3532345859],
 [-0.0158908916, 0.0181292762, 0.0917113604],
 [-0.1522781168,-0.3409913697,-0.0000007362],
 [-0.0063821715, 0.6947952006, 0.2131056766],
 [-0.7231023900, 0.0127783589,-2.1375592252],
 [-0.2035256543, 2.2788946007,-0.0000010351],
 [-0.0063821716, 0.6947951795,-0.2131056766],
 [-0.7231023702, 0.0127783579, 2.1375592251],
 [ 0.2035256536,-2.2788945997,-0.0000010340],
])

# Same, (P)-H2O2/cc-pVDZ - a real virtual space (virtuals in every irrep,
# polarization functions) that STO-3G's two virtuals cannot provide.
AAT_REF_CCPVDZ = np.array([
 [-0.0086864882,  0.0460210947, -0.2786642140],
 [-0.0144315579,  0.0047404923, -0.0413297936],
 [ 0.2754861449,  0.2323528949, -0.0000004948],
 [-0.0086864882,  0.0460210948,  0.2786642140],
 [-0.0144315596,  0.0047404909,  0.0413297941],
 [-0.2754861451, -0.2323528949, -0.0000004934],
 [-0.0086586168,  0.2907045614,  0.1612513739],
 [-0.3149341376,  0.0125920517, -0.6588530005],
 [-0.2451662663,  0.7559376141, -0.0000003548],
 [-0.0086586161,  0.2907045538, -0.1612513739],
 [-0.3149341301,  0.0125920510,  0.6588530000],
 [ 0.2451662660, -0.7559376135, -0.0000003548],
])


def test_cisd_aat_vs_reference(cisd_h2o2):
    """The facade total reproduces the standalone validated reference, every
    element (STO-3G)."""
    P = np.asarray(pycc.aat(pycc.CIderiv(cisd_h2o2())).total).reshape(-1, 3)
    print(P)
    assert np.max(np.abs(P - AAT_REF)) < 1e-8, np.max(np.abs(P - AAT_REF))


def test_cisd_aat_ccpvdz_vs_reference(cisd_h2o2):
    """Larger basis (cc-pVDZ): the facade total reproduces the standalone
    validated reference, every element."""
    P = np.asarray(pycc.aat(pycc.CIderiv(cisd_h2o2(basis='cc-pVDZ'))).total).reshape(-1, 3)
    print(P)
    assert np.max(np.abs(P - AAT_REF_CCPVDZ)) < 1e-9, np.max(np.abs(P - AAT_REF_CCPVDZ))

# (P)-hydrogen peroxide, apyib manuscript geometry (a.u.); atom order H,H,O,O 
APYIB_H2O2 = """
H -1.780954530308296   1.411647335546379   0.872055376436941
H  1.780954530308296  -1.411647335546379   0.872055376436941
O -1.371214332646589  -0.115525249760340  -0.054947416764017
O  1.371214332646589   0.115525249760340  -0.054947416764017
no_com
no_reorient
symmetry c1
units bohr
"""

# apyib reference ELECTRONIC AATs [3*atom + alpha, beta], keyed by the psi4 freeze_core string.
AAT_APYIB_H2O2 = {
    'false': np.array([
     [-0.0068048716,  0.0213593319,  0.0157638619],
     [ 0.1059075747, -0.1346215832,  0.3154829840],
     [-0.1816121315, -0.1870490984,  0.1457004078],
     [-0.0068048716,  0.0213593319, -0.0157638619],
     [ 0.1059075747, -0.1346215832, -0.3154829840],
     [ 0.1816121315,  0.1870490984,  0.1457004078],
     [ 0.0006046470,  0.0925073148, -0.1257421017],
     [-0.0723391420, -0.1671952961,  0.6366666867],
     [ 0.1734247390, -0.5586888980,  0.1657068045],
     [ 0.0006046470,  0.0925073148,  0.1257421017],
     [-0.0723391420, -0.1671952961, -0.6366666867],
     [-0.1734247390,  0.5586888980,  0.1657068045]]),
    'true': np.array([
     [-0.0068036311,  0.0213660511,  0.0157591711],
     [ 0.1059122164, -0.1346189342,  0.3154831868],
     [-0.1816209684, -0.1870531634,  0.1456979226],
     [-0.0068036311,  0.0213660511, -0.0157591711],
     [ 0.1059122164, -0.1346189342, -0.3154831868],
     [ 0.1816209684,  0.1870531634,  0.1456979226],
     [ 0.0006036703,  0.0925366697, -0.1258237771],
     [-0.0723458976, -0.1671863324,  0.6367516777],
     [ 0.1734516532, -0.5588094273,  0.1656973671],
     [ 0.0006036703,  0.0925366697,  0.1258237771],
     [-0.0723458976, -0.1671863324, -0.6367516777],
     [-0.1734516532,  0.5588094273,  0.1656973671]]),
}

APYIB_TOL_H2O2 = 1e-10         

GAUGES = ('canonical', 'non-canonical')


def _ciwfn(freeze_core='false', geom=APYIB_H2O2, basis='STO-3G'):
    """Converged spatial CISD wavefunction (the CIderiv path is spatial-only, so there is no
    orbital_basis knob as in test_072's _mpwfn)."""
    psi4.core.clean()
    psi4.core.clean_options()
    psi4.geometry(geom)
    psi4.set_options({'basis': basis, 'scf_type': 'pk', 'freeze_core': freeze_core,
                      'e_convergence': 1e-13, 'd_convergence': 1e-13})
    _, wfn = psi4.energy('scf', return_wfn=True)
    ci = pycc.CIwfn(wfn, model='CISD', orbital_basis='spatial')
    ci.solve_ci(e_conv=1e-13, r_conv=1e-13, maxiter=250)
    return ci


def test_cisd_aat_all_electron_vs_apyib():
    """All-electron spatial CISD electronic AAT (SCF reference + correlation, via the pycc.aat
    facade) reproduces the apyib reference for (P)-H2O2/STO-3G, in both orbital gauges."""
    ci = _ciwfn()
    cd = pycc.CIderiv(ci)
    for gauge in GAUGES:
        P = np.asarray(pycc.aat(cd, orbital_gauge=gauge).electronic).reshape(-1, 3)
        d = np.max(np.abs(P - AAT_APYIB_H2O2['false']))
        assert d < APYIB_TOL_H2O2, (gauge, d)


def test_cisd_aat_frozen_core_vs_apyib():
    """Frozen-core spatial CISD electronic AAT reproduces the independent apyib frozen-core
    reference (all-electron SCF reference + frozen-core correlation), in both orbital gauges."""
    ci = _ciwfn(freeze_core='true')
    assert ci.nfzc == 2, ci.nfzc
    cd = pycc.CIderiv(ci)
    for gauge in GAUGES:
        P = np.asarray(pycc.aat(cd, orbital_gauge=gauge).electronic).reshape(-1, 3)
        d = np.max(np.abs(P - AAT_APYIB_H2O2['true']))
        assert d < APYIB_TOL_H2O2, (gauge, d)

        
def test_cisd_aat_gauge_invariance():
    """The CISD correlation AAT is invariant to the orbital gauge of the redundant magnetic
    oo/vv response (non-canonical vs canonical), all-electron and frozen-core.  With a
    frozen core the two choices genuinely differ: non-canonical zeroes the redundant
    within-space rotations and fills only the non-redundant core<->active-occupied block, while
    canonical fills every oo/vv block."""
    for fc in ('false', 'true'):
        ci = _ciwfn(fc)
        nc = np.asarray(pycc.CIderiv(ci).atomic_axial_tensors(gauge='non-canonical'))
        ca = np.asarray(pycc.CIderiv(ci).atomic_axial_tensors(gauge='canonical'))
        assert np.max(np.abs(nc - ca)) < 1e-9, (fc, np.max(np.abs(nc - ca)))

