"""
CISD length-gauge atomic polar tensors - CIwfn.dipole_derivatives() (the\ncorrelation block) through the pycc.apt facade: Lagrangian / Z-vector formulation\nwith fully analytic dz/dR (Krishnan, Shumberger & Crawford).

Reference generated by the standalone validated CISD-VCD
implementation (cisd_vcd.py / cisd_apt_lg.py / cisd_analytic_hessian.py;
A. Krishnan, June 2026), at the geometry below.  That implementation was
itself validated independently: the analytic Hessian against Psi4/Gaussian
finite differences (~1e-6), the AATs against the determinant-based apyib
reference (B. Shumberger; ~1e-11 a.u.), and the LG-APT (Z-vector route)
against finite differences of the analytic dipole.  The CIwfn port
reproduces these values to ~1e-10; the test tolerance (1e-6) absorbs the
printed precision of the reference.  The references are TOTAL tensors, so
the tests exercise the full facade decomposition (nuclear + HF reference +
CISD correlation).  Spatial orbitals, all-electron only.
"""

import numpy as np
import pycc


# Reference TOTAL LG APT [3*atom + beta, alpha], (P)-H2O2/STO-3G.
LG_APT_REF = np.array([
 [ 0.1326162556, 0.0627497934,-0.0000000461],
 [ 0.0788409115,-0.2034439684, 0.0000012770],
 [-0.0000002480, 0.0000011653, 0.2541017267],
 [ 0.1326162556, 0.0627497934, 0.0000000467],
 [ 0.0788409115,-0.2034439684,-0.0000012743],
 [ 0.0000002485,-0.0000011624, 0.2541017267],
 [-0.1326162556,-0.0627497934,-0.0000000387],
 [-0.0788409115, 0.2034439684,-0.0000017648],
 [-0.0000000825,-0.0000014301,-0.2541017267],
 [-0.1326162556,-0.0627497934, 0.0000000381],
 [-0.0788409115, 0.2034439684, 0.0000017621],
 [ 0.0000000820, 0.0000014273,-0.2541017267],
])


def test_cisd_lg_apt_vs_reference(cisd_h2o2):
    """The facade total (nuclear + HF reference + CISD correlation) reproduces
    the standalone validated reference, every element."""
    P = np.asarray(pycc.apt(cisd_h2o2()).total).reshape(-1, 3)
    assert np.max(np.abs(P - LG_APT_REF)) < 1e-9, np.max(np.abs(P - LG_APT_REF))

def test_cisd_lg_apt_translational_sum_rule(cisd_h2o2):
    """Acoustic sum rule: the total LG APT of neutral H2O2 sums to zero over
    atoms; the correlation block alone also sums to zero (traceless corr
    density)."""
    comp = pycc.apt(cisd_h2o2())
    assert np.max(np.abs(np.sum(np.asarray(comp.total), axis=0))) < 1e-9
    assert np.max(np.abs(np.sum(np.asarray(comp.correlation), axis=0))) < 1e-9
