"""
CISD length-gauge atomic polar tensors - pycc.apt(pycc.CIderiv(ci)) facade. 
dipole_derivatives() is inherited from CorrelatedDerivs (the 2n+1 route), 
driven by CIderiv's density hooks - no CISD-specific APT code.

Reference generated by the standalone validated CISD-VCD
implementation (cisd_vcd.py / cisd_apt_lg.py / cisd_analytic_hessian.py;
A. Krishnan, June 2026), at the geometry below.  That implementation was
itself validated independently: the analytic Hessian against Psi4/Gaussian
finite differences, the AATs against the determinant-based apyib
reference (B. Shumberger; ~1e-11 a.u.), and the LG-APT (Z-vector route)
against finite differences of the analytic dipole.  The CIwfn port
reproduces these values to ~1e-10; the test tolerance absorbs the
printed precision of the reference.  The references are TOTAL tensors, so
the tests exercise the full facade decomposition (nuclear + HF reference +
CISD correlation).  Spatial orbitals.  Structured to mirror test_068_mp2_apt: all-electron and
frozen-core in one module, a local wavefunction factory, and correlation-APT components keyed by
the psi4 freeze_core string.
"""

import numpy as np
import psi4

import pycc


# Reference TOTAL LG APT [3*atom + beta, alpha], (P)-H2O2/STO-3G.
LG_APT_REF = np.array([
 [ 0.1326162556, 0.0627497934,-0.0000000461],
 [ 0.0788409115,-0.2034439684, 0.0000012770],
 [-0.0000002480, 0.0000011653, 0.2541017267],
 [ 0.1326162556, 0.0627497934, 0.0000000467],
 [ 0.0788409115,-0.2034439684,-0.0000012743],
 [ 0.0000002485,-0.0000011624, 0.2541017267],
 [-0.1326162556,-0.0627497934,-0.0000000387],
 [-0.0788409115, 0.2034439684,-0.0000017648],
 [-0.0000000825,-0.0000014301,-0.2541017267],
 [-0.1326162556,-0.0627497934, 0.0000000381],
 [-0.0788409115, 0.2034439684, 0.0000017621],
 [ 0.0000000820, 0.0000014273,-0.2541017267],
])


# (P)-H2O2 at the CISD-VCD validation geometry (bohr) - the same geometry the cisd_h2o2 fixture
# builds, in explicit array form so the FD recipe below can displace a single coordinate.
SYM = ['H', 'H', 'O', 'O']
BASE = np.array([[-1.938703940499,  1.630081390557, 0.408551539155],
                 [ 1.938703940499, -1.630081390557, 0.408551534619],
                 [-1.364718227128, -0.236825138192, 0.408556429577],
                 [ 1.364718227128,  0.236825138192, 0.408556416160]])


def _geom(coords):
    s = "units bohr\nsymmetry c1\nno_com\nno_reorient\n"
    for sym, xyz in zip(SYM, coords):
        s += f"{sym} {xyz[0]:.10f} {xyz[1]:.10f} {xyz[2]:.10f}\n"
    return s


def _cideriv(coords=BASE, freeze_core='false', basis='sto-3g'):
    """Converged spatial CISD derivative driver."""
    psi4.core.clean()
    psi4.core.clean_options()
    psi4.geometry(_geom(coords))
    psi4.set_options({'basis': basis, 'scf_type': 'pk', 'freeze_core': freeze_core,
                      'e_convergence': 1e-13, 'd_convergence': 1e-13})
    _, wfn = psi4.energy('scf', return_wfn=True)
    ci = pycc.CIwfn(wfn, model='CISD', orbital_basis='spatial')
    ci.solve_ci(e_conv=1e-13, r_conv=1e-13, maxiter=250)
    return pycc.CIderiv(ci)


def _corr_dipfd(alpha, atom, cart, freeze_core='false', h=0.002):
    """Regeneration recipe for APT_CORR (not run in the tests): P_corr[atom, cart, alpha] via a
    7-point O(h^6) FD of the analytic correlation dipole - the first-order relaxed dipole, which
    is independent of the 2n+1 second-derivative code the frozen values validate."""
    def mu(delta):
        c = BASE.copy()
        c[atom, cart] += delta
        return _cideriv(c, freeze_core).relaxed_dipole()[alpha]
    return (-mu(-3 * h) + 9 * mu(-2 * h) - 45 * mu(-h)
            + 45 * mu(h) - 9 * mu(2 * h) + mu(3 * h)) / (60 * h)


# Frozen analytic correlation APT components, (alpha, atom, cart) -> P_corr[atom, cart, alpha],
# keyed by the psi4 freeze_core string.  Each validated once against _corr_dipfd above
# (8e-13 to 1.7e-11); analytic values, frozen rather than re-run.
APT_CORR = {
    'false': {
        (2, 0, 2): -0.026037068327921298,
        (1, 2, 1):  0.09680636658274777,
        (2, 2, 1): -1.359101875484379e-07,
        (0, 0, 0): -0.022561685194105025,
    },
    'true': {
        (2, 0, 2): -0.026003824547506296,
        (1, 2, 1):  0.09676849959897356,
        (2, 2, 1): -1.3578673440645287e-07,
        (0, 0, 0): -0.0225184644441816,
    },
}



# The apyib reference water geometry
GAUGE_WATER = """
O -0.000000000000000   0.000000000000000   0.128444410656440
H  0.000000000000000  -1.415531238764228  -1.019253001167221
H  0.000000000000000   1.415531238764228  -1.019253001167221
units bohr
symmetry c1
no_com
no_reorient
"""


def _cideriv_water(freeze_core='false', basis='6-31G'):
    """CISD derivative driver on water (no near-degenerate occupied orbitals)."""
    psi4.core.clean()
    psi4.core.clean_options()
    psi4.geometry(GAUGE_WATER)
    psi4.set_options({'basis': basis, 'scf_type': 'pk', 'freeze_core': freeze_core,
                      'e_convergence': 1e-13, 'd_convergence': 1e-13})
    _, wfn = psi4.energy('scf', return_wfn=True)
    ci = pycc.CIwfn(wfn, model='CISD', orbital_basis='spatial')
    ci.solve_ci(e_conv=1e-13, r_conv=1e-13, maxiter=250)
    return pycc.CIderiv(ci)

def test_cisd_lg_apt_vs_reference(cisd_h2o2):
    """The facade total (nuclear + HF reference + CISD correlation) reproduces
    the standalone validated reference, every element."""
    P = np.asarray(pycc.apt(pycc.CIderiv(cisd_h2o2())).total).reshape(-1, 3)
    assert np.max(np.abs(P - LG_APT_REF)) < 1e-9, np.max(np.abs(P - LG_APT_REF))

def test_cisd_lg_apt_corr_dipfd():
    """All-electron spatial correlation LG APT vs its frozen reference (validated once against a
    7-point dipole-over-nuclear FD to ~1e-11), representative components."""
    P = _cideriv().dipole_derivatives()
    for (alpha, atom, cart), ref in APT_CORR['false'].items():
        assert abs(P[atom, cart, alpha] - ref) < 1e-9, (alpha, atom, cart, P[atom, cart, alpha], ref)


def test_cisd_lg_apt_corr_dipfd_frozen_core():
    """Frozen-core spatial correlation LG APT vs its frozen reference (validated once against the
    same 7-point dipole-over-nuclear FD), representative components.

    Exercises the mixed field/nuclear core<->active response: the frozen-core nuclear density
    response over the active space, coupled to the core<->active orbital relaxation.  Needs no
    APT-specific code - the ncore machinery carries over from the gradient and the Z-vector."""
    cd = _cideriv(freeze_core='true')
    assert cd.ci.nfzc == 2, cd.ci.nfzc
    P = cd.dipole_derivatives()
    for (alpha, atom, cart), ref in APT_CORR['true'].items():
        assert abs(P[atom, cart, alpha] - ref) < 1e-9, (alpha, atom, cart, P[atom, cart, alpha], ref)


def test_cisd_lg_apt_translational_sum_rule(cisd_h2o2):
    """Acoustic sum rule: the total LG APT of neutral H2O2 sums to zero over
    atoms; the correlation block alone also sums to zero (traceless corr
    density).  All-electron and frozen-core (mirrors test_068's all-electron /
    ``test_fc_`` sum-rule pair)."""
    for fc in (False, True):
        comp = pycc.apt(pycc.CIderiv(cisd_h2o2(freeze_core=fc)))
        assert np.max(np.abs(np.sum(np.asarray(comp.total), axis=0))) < 1e-9, fc
        assert np.max(np.abs(np.sum(np.asarray(comp.correlation), axis=0))) < 1e-9, fc


def test_cisd_lg_apt_2n1_routes_agree(cisd_h2o2):
    """The two 2n+1 routes give the same correlation LG APT, all-electron and frozen-core -
    the CISD analogue of test_068's ``test_mp2_apt_2n1_routes_agree_631g``.  ``'2n+1-field'``
    (the default, 3 field responses) and '2n+1-nuclear' (3N nuclear responses) share the
    density hooks but drive entirely different perturbed solves, so agreement is a genuine
    cross-check of the frozen-core perturbed Z-vector rather than a restatement."""
    for fc in (False, True):
        cd = pycc.CIderiv(cisd_h2o2(freeze_core=fc))
        field = np.asarray(cd.dipole_derivatives(route='2n+1-field'))
        nuc = np.asarray(cd.dipole_derivatives(route='2n+1-nuclear'))
        assert np.max(np.abs(field - nuc)) < 1e-9, (fc, np.max(np.abs(field - nuc)))


def test_cisd_lg_apt_perturbed_mo_gauge_invariance():
    """The correlation LG APT is invariant to the perturbed-MO gauge (non-canonical vs the
    canonical dependent-pair route), all-electron and frozen-core. """
    for fc in ('false', 'true'):
        nc = np.asarray(_cideriv_water(fc).dipole_derivatives())
        cd = _cideriv_water(fc)
        cd._gauge_override = 'canonical'
        ca = np.asarray(cd.dipole_derivatives())
        assert np.max(np.abs(nc - ca)) < 1e-9, (fc, np.max(np.abs(nc - ca)))
