"""
CISD velocity-gauge atomic polar tensors - pycc.apt(pycc.CIderiv(ci), gauge='velocity') facade. 
velocity_dipole_derivatives() is CISD-specific (a wave-function-overlap construction the base does not provide), -2*(Icc+Icphi+Iphic+Iphiphi) with the vector-potential CPCI response.

Reference generated by the standalone validated CISD-VCD
implementation (cisd_vcd.py / cisd_apt_lg.py / cisd_analytic_hessian.py;
A. Krishnan, June 2026), at the geometry below.  That implementation was
itself validated independently: the analytic Hessian against Psi4/Gaussian
finite differences, the AATs against the determinant-based apyib
reference (B. Shumberger; ~1e-11 a.u.), and the LG-APT (Z-vector route)
against finite differences of the analytic dipole.  The CIwfn port
reproduces these values to ~1e-10.  The references are TOTAL tensors, so
the tests exercise the full facade decomposition (nuclear + HF reference +
CISD correlation).  Spatial orbitals.  Structured to mirror test_073_mp2_vg_apt: all-electron
and frozen-core in one module, a local wavefunction factory, and references keyed by the psi4
freeze_core string.
"""

import numpy as np
import psi4

import pycc
from .conftest import CISD_H2O2_GEOM


# Reference TOTAL VG APT [3*atom + beta, alpha], (P)-H2O2/STO-3G.
VG_APT_REF = np.array([
 [ 0.9565985610, 0.2404439930,-0.0000006788],
 [ 0.1774893329, 0.1555861277, 0.0000019628],
 [-0.0000004434, 0.0000018991, 0.8551121460],
 [ 0.9565985610, 0.2404439930, 0.0000006761],
 [ 0.1774893329, 0.1555861277,-0.0000019592],
 [ 0.0000004413,-0.0000018960, 0.8551121460],
 [ 6.8024442952, 0.0624854667,-0.0000009738],
 [ 0.1250980895, 7.0795865038, 0.0000030620],
 [-0.0000011688, 0.0000029529, 8.0926181418],
 [ 6.8024442952, 0.0624854667, 0.0000009844],
 [ 0.1250980895, 7.0795865038,-0.0000030555],
 [ 0.0000011790,-0.0000029459, 8.0926181418],
])


# (P)-hydrogen peroxide (a.u.); atom order H,H,O,O.  
APYIB_H2O2 = """
H -1.780954530308296   1.411647335546379   0.872055376436941
H  1.780954530308296  -1.411647335546379   0.872055376436941
O -1.371214332646589  -0.115525249760340  -0.054947416764017
O  1.371214332646589   0.115525249760340  -0.054947416764017
no_com
no_reorient
symmetry c1
units bohr
"""

# Independent reference TOTAL VG APT [3*atom + beta, alpha] at APYIB_H2O2 / STO-3G, keyed by the
# psi4 freeze_core string.  TOTAL, not electronic.
VG_APT_APYIB_H2O2 = {
    'true': np.array([
     [ 0.9711654998,  0.1846681243,  0.1120022625],
     [ 0.0993017000,  0.2878369473, -0.3602514291],
     [ 0.0575918008, -0.3612872774,  0.6387739088],
     [ 0.9711654998,  0.1846681243, -0.1120022625],
     [ 0.0993017000,  0.2878369473,  0.3602514291],
     [-0.0575918008,  0.3612872774,  0.6387739088],
     [ 6.8173244621,  0.0447833993,  0.1492705591],
     [ 0.1296657694,  7.3361450221, -0.5452487772],
     [ 0.2262202391, -0.5297704016,  7.8286092018],
     [ 6.8173244621,  0.0447833993, -0.1492705591],
     [ 0.1296657694,  7.3361450221,  0.5452487772],
     [-0.2262202391,  0.5297704016,  7.8286092018]]),
}

APYIB_TOL = 1e-10        # observed agreement ~4.5e-11, both gauges

GAUGES = ('canonical', 'non-canonical')


def _ciwfn(freeze_core='false', geom=CISD_H2O2_GEOM, basis='sto-3g'):
    """Converged spatial CISD wavefunction at the reference geometry, returned with the psi4
    wavefunction (needed for the HF-limit comparison)."""
    psi4.core.clean()
    psi4.core.clean_options()
    psi4.geometry(geom)
    psi4.set_options({'basis': basis, 'scf_type': 'pk', 'freeze_core': freeze_core,
                      'e_convergence': 1e-13, 'd_convergence': 1e-13})
    _, wfn = psi4.energy('scf', return_wfn=True)
    ci = pycc.CIwfn(wfn, model='CISD', orbital_basis='spatial')
    ci.solve_ci(e_conv=1e-13, r_conv=1e-13, maxiter=250)
    return ci, wfn


def test_cisd_vg_apt_all_electron(cisd_h2o2):
    """All-electron spatial CISD VG APT (total, via the pycc.apt velocity-gauge facade)
    reproduces the standalone validated reference, every element."""
    ci = cisd_h2o2()
    for orbital_gauge in GAUGES:
        P = np.asarray(pycc.apt(pycc.CIderiv(ci), gauge='velocity',
                                orbital_gauge=orbital_gauge).total).reshape(-1, 3)
        d = np.max(np.abs(P - VG_APT_REF))
        assert d < 1e-9, (orbital_gauge, d)


def test_cisd_vg_apt_frozen_core_vs_apyib():
    """Frozen-core spatial CISD VG APT (total, via the pycc.apt velocity-gauge facade)
    reproduces the independent reference at the apyib geometry, in both orbital gauges."""
    ci = _ciwfn('true', APYIB_H2O2, 'STO-3G')[0]
    assert ci.nfzc == 2, ci.nfzc
    for gauge in GAUGES:
        P = np.asarray(pycc.apt(pycc.CIderiv(ci), gauge='velocity',
                                orbital_gauge=gauge).total).reshape(-1, 3)
        d = np.max(np.abs(P - VG_APT_APYIB_H2O2['true']))
        assert d < APYIB_TOL, (gauge, d)


def test_cisd_vg_apt_gauge_invariance():
    """The CISD correlation VG APT is invariant to the orbital gauge of the redundant momentum
    oo/vv response (non-canonical vs canonical), all-electron and frozen-core."""
    for fc in ('false', 'true'):
        ci = _ciwfn(fc)[0]
        nc = np.asarray(pycc.CIderiv(ci).apt(gauge='velocity', orbital_gauge='non-canonical').correlation)
        ca = np.asarray(pycc.CIderiv(ci).apt(gauge='velocity', orbital_gauge='canonical').correlation)
        assert np.max(np.abs(nc - ca)) < 1e-9, (fc, np.max(np.abs(nc - ca)))


