"""
CISD molecular (nuclear) Hessian - CIwfn.hessian() (the correlation block)\nthrough the pycc.hessian facade: the explicit nuclear-nuclear second derivative\nwith the Z-vector replacement for U^{XY} (T0-T5 assembly).

Reference provenance: generated by the standalone validated CISD-VCD
implementation (cisd_vcd.py / cisd_apt_lg.py / cisd_analytic_hessian.py;
A. Krishnan, June 2026), at the geometry below.  That implementation was
itself validated independently: the analytic Hessian against Psi4/Gaussian
finite differences (~1e-6), the AATs against the determinant-based apyib
reference (B. Shumberger; ~1e-11 a.u.), and the LG-APT (Z-vector route)
against finite differences of the analytic dipole.  The CIwfn port
reproduces these values to ~1e-10; the test tolerance (1e-6) absorbs the
printed precision of the reference.  The references are TOTAL tensors, so
the tests exercise the full facade decomposition (nuclear + HF reference +
CISD correlation).  Spatial orbitals, all-electron only.
"""

import numpy as np
import pycc


# Reference TOTAL Hessian (3*natom x 3*natom), (P)-H2O2/STO-3G.
HESS_REF = np.array([
 [ 1.17440123e-01,-1.17600481e-01, 3.11374866e-07,-1.48695362e-02,-2.50929462e-03,-3.08954088e-08,-8.22972776e-02, 5.74035675e-02,-2.00683390e-07,-2.02733091e-02, 6.27062078e-02,-7.97960671e-08],
 [-1.17600481e-01, 4.50462612e-01,-1.16352630e-06,-2.50929462e-03, 1.46156262e-03, 1.09056100e-08, 1.35095225e-01,-4.63127973e-01, 1.19522046e-06,-1.49854499e-02, 1.12037981e-02,-4.25997658e-08],
 [ 3.11374866e-07,-1.16352630e-06, 2.75322865e-04, 3.10434256e-08,-1.08929178e-08, 2.75320484e-04,-3.32210280e-07, 1.21055938e-06,-2.75318530e-04,-1.02080115e-08,-3.61401606e-08,-2.75324818e-04],
 [-1.48695362e-02,-2.50929462e-03, 3.10434256e-08, 1.17440123e-01,-1.17600481e-01,-3.11507979e-07,-2.02733091e-02, 6.27062078e-02, 7.95038908e-08,-8.22972776e-02, 5.74035675e-02, 2.00960663e-07],
 [-2.50929462e-03, 1.46156262e-03,-1.08929178e-08,-1.17600481e-01, 4.50462612e-01, 1.16120663e-06,-1.49854499e-02, 1.12037981e-02, 4.26431001e-08, 1.35095225e-01,-4.63127973e-01,-1.19295682e-06],
 [-3.08954088e-08, 1.09056100e-08, 2.75320484e-04,-3.11507979e-07, 1.16120663e-06, 2.75322865e-04, 1.04896705e-08, 3.55192597e-08,-2.75324818e-04, 3.31913717e-07,-1.20763150e-06,-2.75318530e-04],
 [-8.22972776e-02, 1.35095225e-01,-3.32210280e-07,-2.02733091e-02,-1.49854499e-02, 1.04896705e-08, 5.10634230e-01,-4.99015461e-02, 2.19445198e-07,-4.08063643e-01,-7.02082292e-02, 1.02275412e-07],
 [ 5.74035675e-02,-4.63127973e-01, 1.21055938e-06, 6.27062078e-02, 1.12037981e-02, 3.55192597e-08,-4.99015461e-02, 5.67806150e-01,-1.24270020e-06,-7.02082292e-02,-1.15881975e-01,-3.37844056e-09],
 [-2.00683390e-07, 1.19522046e-06,-2.75318530e-04, 7.95038908e-08, 4.26431001e-08,-2.75324818e-04, 2.19445198e-07,-1.24270020e-06, 2.75281709e-04,-9.82656981e-08, 4.83664127e-09, 2.75361639e-04],
 [-2.02733091e-02,-1.49854499e-02,-1.02080115e-08,-8.22972776e-02, 1.35095225e-01, 3.31913717e-07,-4.08063643e-01,-7.02082292e-02,-9.82656981e-08, 5.10634230e-01,-4.99015461e-02,-2.23440008e-07],
 [ 6.27062078e-02, 1.12037981e-02,-3.61401606e-08, 5.74035675e-02,-4.63127973e-01,-1.20763150e-06,-7.02082292e-02,-1.15881975e-01, 4.83664127e-09,-4.99015461e-02, 5.67806150e-01, 1.23893502e-06],
 [-7.97960671e-08,-4.25997658e-08,-2.75324818e-04, 2.00960663e-07,-1.19295682e-06,-2.75318530e-04, 1.02275412e-07,-3.37844056e-09, 2.75361639e-04,-2.23440008e-07, 1.23893502e-06, 2.75281709e-04],
])


def test_cisd_hessian_vs_reference(cisd_h2o2):
    """The facade total (nuclear repulsion + HF reference + CISD correlation)
    reproduces the standalone validated reference, every element."""
    H = np.asarray(pycc.hessian(cisd_h2o2()).total)
    assert np.max(np.abs(H - HESS_REF)) < 1e-6, np.max(np.abs(H - HESS_REF))


def test_cisd_hessian_symmetry_sum_rule(cisd_h2o2):
    """The total Hessian is symmetric and
    translationally invariant (sum over the second atom vanishes); the
    correlation block obeys both on its own."""
    comp = pycc.hessian(cisd_h2o2())
    for H in (np.asarray(comp.total), np.asarray(comp.correlation)):
        assert np.max(np.abs(H - H.T)) < 1e-8
        assert np.max(np.abs(H.reshape(4, 3, 4, 3).sum(axis=2))) < 1e-6
