# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

# In case the project was not installed
import os
import sys
sys.path.insert(0, os.path.abspath('..'))


# -- Project information -----------------------------------------------------

project = 'PyCC'
copyright = ("2021, T Daniel Crawford. Project structure based on the "
             "Computational Molecular Science Python Cookiecutter version 1.5")
author = 'T Daniel Crawford'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autosummary',
    'sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.intersphinx',
    'sphinx.ext.extlinks',
]

autosummary_generate = True

# psi4 is conda-only (not pip-installable), so the docs builder mocks it: the package
# is imported only to read docstrings/signatures for autosummary, and psi4 is used
# inside method bodies, never at import time. torch is left unmocked -- it is already
# guarded by a try/except in the package, so its absence is handled normally.
autodoc_mock_imports = ['psi4']

# Document members in source order (preserving each module's labeled-section grouping) rather
# than alphabetically.
autodoc_member_order = 'bysource'

# Document all members by default, including PRIVATE (underscore-prefixed) ones -- much of pycc's
# substantive documentation (the derivations) lives on private methods.  To hide specific members:
#   * per module: add e.g. ``:exclude-members: _foo, _bar`` under its ``automodule`` in api.rst;
#   * a member's own docstring: add a ``:meta private:`` line (it still shows while private-members
#     is on, but is a stable marker) -- to force-hide, use exclude-members or the skip handler below;
#   * globally by name/pattern: see the ``autodoc-skip-member`` handler stub in ``setup()`` at the
#     bottom of this file.
autodoc_default_options = {
    'members': True,
    'private-members': True,
}

# Merge each class's ``__init__`` docstring into the class documentation.  The autodoc default
# ('class') renders only the class docstring, so an ``__init__`` docstring -- where the
# construction / integral-build math is documented (e.g. Hamiltonian, CPHF, the deriv drivers) --
# would otherwise never appear.
autoclass_content = 'both'

napoleon_google_docstring = False
napoleon_use_param = False
napoleon_use_ivar = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'default'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'pyccdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'pycc.tex', 'PyCC Documentation',
     'pycc', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'pycc', 'PyCC Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'pycc', 'PyCC Documentation',
     author, 'pycc', 'A Python-based coupled cluster implementation.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------

# Optional: drop specific members from autodoc by name/pattern across the whole build (private
# members are on by default; this is how you carve exceptions back out).  Uncomment and edit:
#
# import re
# _HIDE_NAMES = set()                         # exact member names to always hide, e.g. {'_scratch'}
# _HIDE_PATTERNS = [re.compile(r'^_debug_')]  # regexes matched against the member name
#
# def _skip_member(app, what, name, obj, skip, options):
#     if name in _HIDE_NAMES or any(p.search(name) for p in _HIDE_PATTERNS):
#         return True                         # True  -> hide this member
#     return None                             # None  -> keep Sphinx's default decision
#
# def setup(app):
#     app.connect('autodoc-skip-member', _skip_member)
